name: "PHP_CodeSniffer"

on: [push]

jobs:
    style:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2
                with:
                  fetch-depth: 0

            -   name: Check style
                uses: chekalsky/phpcs-action@v1
                with:
                  enable_warnings: true
